export const enum BLOCK_TYPES {
  BOOKMARK = "bookmark",
  BREADCRUMB = "breadcrumb",
  BULLETED_LIST_ITEM = "bulleted_list_item",
  CALLOUT = "callout",
  CHILD_DATABASE = "child_database",
  CHILD_PAGE = "child_page",
  COLUMN = "column",
  COLUMN_LIST = "column_list",
  DIVIDER = "divider",
  EMBED = "embed",
  EQUATION = "equation",
  FILE = "file",
  HEADING_1 = "heading_1",
  HEADING_2 = "heading_2",
  HEADING_3 = "heading_3",
  IMAGE = "image",
  LINK_PREVIEW = "link_preview",
  LINK_TO_PAGE = "link_to_page",
  NUMBERED_LIST_ITEM = "numbered_list_item",
  PARAGRAPH = "paragraph",
  PDF = "pdf",
  QUOTE = "quote",
  SYNCED_BLOCK = "synced_block",
  TABLE = "table",
  TABLE_OF_CONTENTS = "table_of_contents",
  TABLE_ROW = "table_row",
  TEMPLATE = "template",
  TO_DO = "to_do",
  TOGGLE = "toggle",
  UNSUPPORTED = "unsupported",
  VIDEO = "video",
  CODE = "code",
}
export const enum PAGE_TYPES {
  EXTERNAL = "external",
  FILE = "file",
  EMOJI = "emoji",
  CHECKBOX = 'checkbox',
  CREATED_BY = 'created_by',
  CREATED_TIME = 'created_time',
  DATE = 'date',
  EMAIL = 'email',
  FILES = 'files',
  FORMULA = 'formula',
  LAST_EDITED_BY = 'last_edited_by',
  LAST_EDITED_TIME = 'last_edited_time',
  MULTI_SELECT = 'multi_select',
  NUMBER = 'number',
  PEOPLE = 'people',
  PHONE_NUMBER = 'phone_number',
  RELATION = 'relation',
  ROLLUP = 'rollup',
  RICH_TEXT = 'rich_text',
  SELECT = 'select',
  STATUS = 'status',
  TITLE = 'title',
  URL = 'url',
}

export const enum ICON_TYPE {
  EMOJI = 'emoji',
  FILE = 'file',
  EXTERNAL ='external'
}
export const enum IMAGE_TYPE {
  FILE = 'file',
  EXTERNAL ='external'
}